version: '3.8'

services:
#  postgres:
#    image: postgres:latest
#    container_name: postgrescontainer
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_DB: casino
#    networks:
#      - appnetwork
#    ports:
#      - "5433:5432"

  app:
    build: .
#    image: mathewgvozdev/casino:latest
    ports:
      - "8081:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: casino
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - appnetwork

volumes:
  postgresql_data:
    driver_opts:
      type: none
      o: bind
      device: /path/to/postgresql_data

networks:
  appnetwork:
    driver: bridge