spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/casino
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: never
