server:
  port: 8080

spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/casino
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
